project:
  type: book

book:
  title: "Introducción al Píxel"
  author: "Norah Jones"
  date: "29/3/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - introLibresprite.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc-title: Contenido
  pdf:
    documentclass: scrreprt
    toc-title: Contenido
  epub:
    toc: true
    toc-title: Contenido
    html-math-method: mathml



