project:
  type: book

book:
  title: "Introducción al Píxel"
  author: "Luis Mendoza"
  chapters:
    - index.qmd
    - intro.qmd
    - fundamentos.qmd
    - introLibresprite.qmd
    - spriteSheets.qmd
    - playerSprite.qmd
    - fondo.qmd
    - baseColor.qmd
    - 1BitPixel.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc-title: Contenido
  pdf:
    documentclass: scrreprt
    toc-title: Contenido
  epub:
    toc: true
    toc-title: Contenido
    html-math-method: mathml



